apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: helm-chart-deployment
  namespace: actions-runner
spec:
  replicas: 1
  template:
    spec:
      repository: rhattox-helm-charts/deployment
      # https://github.com/actions/actions-runner-controller/blob/master/docs/deploying-alternative-runners.md
      image: summerwind/actions-runner-dind
      dockerdWithinRunnerContainer: true
      dockerMTU: 1450
      env:
        - name: ARC_DOCKER_MTU_PROPAGATION
          value: "true"