{{- if .Values.horizontalPodAutoscaler }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ printf "%s-%s" ("hpa") (include "my-app.fullname" .) | quote}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ printf "%s-%s" ("deployment") (include "my-app.fullname" .) | quote}}
  minReplicas: {{ required "HPA minReplicas missing!!" .Values.horizontalPodAutoscaler.minReplicas | int }}
  maxReplicas: {{ required "HPA maxReplicas missing!!" .Values.horizontalPodAutoscaler.maxReplicas | int }}
  metrics: {{ required "HPA metrics missing!!" .Values.horizontalPodAutoscaler.metrics | toYaml | nindent 4}}
{{- end }}